export interface Product {
  id: number;
  name: string;
}

export interface Category {
  CategoryId: number;
  CategoryName: string;
  Description: string;
  Products: number[];
  SimpleProducts: string[];
}

export const categories: Category[] = [
  {
    CategoryId: 1,
    CategoryName: 'Beverages',
    Description: 'Soft drinks, coffees, teas, beers, and ales',
    Products: [1, 2, 24, 34, 35, 38, 39, 43, 67, 70, 75, 76],
    SimpleProducts: [
      'Chai',
      'Chang',
      'Guaraná Fantástica',
      'Sasquatch Ale',
      'Steeleye Stout',
      'Côte de Blaye',
      'Chartreuse verte',
      'Ipoh Coffee',
      'Laughing Lumberjack Lager',
      'Outback Lager',
      'Rhönbräu Klosterbier',
      'Lakkalikööri',
    ],
  },
  {
    CategoryId: 2,
    CategoryName: 'Condiments',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    Products: [3, 4, 5, 6, 8, 15, 44, 61, 63, 65, 66, 77],
    SimpleProducts: [
      'Aniseed Syrup',
      "Chef Anton's Cajun Seasoning",
      "Chef Anton's Gumbo Mix",
      "Grandma's Boysenberry Spread",
      'Northwoods Cranberry Sauce',
      'Genen Shouyu',
      'Gula Malacca',
      "Sirop d'érable",
      'Vegie-spread',
      'Louisiana Fiery Hot Pepper Sauce',
      'Louisiana Hot Spiced Okra',
      'Original Frankfurter grüne Soße',
    ],
  },
  {
    CategoryId: 3,
    CategoryName: 'Confections',
    Description: 'Desserts, candies, and sweet breads',
    Products: [16, 19, 20, 21, 25, 26, 27, 47, 48, 49, 50, 62, 68],
    SimpleProducts: [
      'Pavlova',
      'Teatime Chocolate Biscuits',
      "Sir Rodney's Marmalade",
      "Sir Rodney's Scones",
      'NuNuCa Nuß-Nougat-Creme',
      'Gumbär Gummibärchen',
      'Schoggi Schokolade',
      'Zaanse koeken',
      'Chocolade',
      'Maxilaku',
      'Valkoinen suklaa',
      'Tarte au sucre',
      'Scottish Longbreads',
    ],
  },
  {
    CategoryId: 4,
    CategoryName: 'Dairy Products',
    Description: 'Cheeses',
    Products: [11, 12, 31, 32, 33, 59, 60, 69, 71, 72],
    SimpleProducts: [
      'Queso Cabrales',
      'Queso Manchego La Pastora',
      'Gorgonzola Telino',
      'Mascarpone Fabioli',
      'Geitost',
      'Raclette Courdavault',
      'Camembert Pierrot',
      'Gudbrandsdalsost',
      'Flotemysost',
      'Mozzarella di Giovanni',
    ],
  },
  {
    CategoryId: 5,
    CategoryName: 'Grains/Cereals',
    Description: 'Breads, crackers, pasta, and cereal',
    Products: [22, 23, 42, 52, 56, 57, 64],
    SimpleProducts: [
      "Gustaf's Knäckebröd",
      'Tunnbröd',
      'Singaporean Hokkien Fried Mee',
      'Filo Mix',
      'Gnocchi di nonna Alice',
      'Ravioli Angelo',
      'Wimmers gute Semmelknödel',
    ],
  },
  {
    CategoryId: 6,
    CategoryName: 'Meat/Poultry',
    Description: 'Prepared meats',
    Products: [9, 17, 29, 53, 54, 55],
    SimpleProducts: [
      'Mishi Kobe Niku',
      'Alice Mutton',
      'Thüringer Rostbratwurst',
      'Perth Pasties',
      'Tourtière',
      'Pâté chinois',
    ],
  },
  {
    CategoryId: 7,
    CategoryName: 'Produce',
    Description: 'Dried fruit and bean curd',
    Products: [7, 14, 28, 51, 74],
    SimpleProducts: [
      "Uncle Bob's Organic Dried Pears",
      'Tofu',
      'Rössle Sauerkraut',
      'Manjimup Dried Apples',
      'Longlife Tofu',
    ],
  },
  {
    CategoryId: 8,
    CategoryName: 'Seafood',
    Description: 'Seaweed and fish',
    Products: [10, 13, 18, 30, 36, 37, 40, 41, 45, 46, 58, 73],
    SimpleProducts: [
      'Ikura',
      'Konbu',
      'Carnarvon Tigers',
      'Nord-Ost Matjeshering',
      'Inlagd Sill',
      'Gravad lax',
      'Boston Crab Meat',
      "Jack's New England Clam Chowder",
      'Rogede sild',
      'Spegesild',
      'Escargots de Bourgogne',
      'Röd Kaviar',
    ],
  },
];

export const products: Product[] = [
  { id: 1, name: 'Chai' },
  { id: 2, name: 'Chang' },
  { id: 3, name: 'Aniseed Syrup' },
  { id: 4, name: "Chef Anton's Cajun Seasoning" },
  { id: 5, name: "Chef Anton's Gumbo Mix" },
  { id: 6, name: "Grandma's Boysenberry Spread" },
  { id: 7, name: "Uncle Bob's Organic Dried Pears" },
  { id: 8, name: 'Northwoods Cranberry Sauce' },
  { id: 9, name: 'Mishi Kobe Niku' },
  { id: 10, name: 'Ikura' },
  { id: 11, name: 'Queso Cabrales' },
  { id: 12, name: 'Queso Manchego La Pastora' },
  { id: 13, name: 'Konbu' },
  { id: 14, name: 'Tofu' },
  { id: 15, name: 'Genen Shouyu' },
  { id: 16, name: 'Pavlova' },
  { id: 17, name: 'Alice Mutton' },
  { id: 18, name: 'Carnarvon Tigers' },
  { id: 19, name: 'Teatime Chocolate Biscuits' },
  { id: 20, name: "Sir Rodney's Marmalade" },
  { id: 21, name: "Sir Rodney's Scones" },
  { id: 22, name: "Gustaf's Knäckebröd" },
  { id: 23, name: 'Tunnbröd' },
  { id: 24, name: 'Guaraná Fantástica' },
  { id: 25, name: 'NuNuCa Nuß-Nougat-Creme' },
  { id: 26, name: 'Gumbär Gummibärchen' },
  { id: 27, name: 'Schoggi Schokolade' },
  { id: 28, name: 'Rössle Sauerkraut' },
  { id: 29, name: 'Thüringer Rostbratwurst' },
  { id: 30, name: 'Nord-Ost Matjeshering' },
  { id: 31, name: 'Gorgonzola Telino' },
  { id: 32, name: 'Mascarpone Fabioli' },
  { id: 33, name: 'Geitost' },
  { id: 34, name: 'Sasquatch Ale' },
  { id: 35, name: 'Steeleye Stout' },
  { id: 36, name: 'Inlagd Sill' },
  { id: 37, name: 'Gravad lax' },
  { id: 38, name: 'Côte de Blaye' },
  { id: 39, name: 'Chartreuse verte' },
  { id: 40, name: 'Boston Crab Meat' },
  { id: 41, name: "Jack's New England Clam Chowder" },
  { id: 42, name: 'Singaporean Hokkien Fried Mee' },
  { id: 43, name: 'Ipoh Coffee' },
  { id: 44, name: 'Gula Malacca' },
  { id: 45, name: 'Rogede sild' },
  { id: 46, name: 'Spegesild' },
  { id: 47, name: 'Zaanse koeken' },
  { id: 48, name: 'Chocolade' },
  { id: 49, name: 'Maxilaku' },
  { id: 50, name: 'Valkoinen suklaa' },
  { id: 51, name: 'Manjimup Dried Apples' },
  { id: 52, name: 'Filo Mix' },
  { id: 53, name: 'Perth Pasties' },
  { id: 54, name: 'Tourtière' },
  { id: 55, name: 'Pâté chinois' },
  { id: 56, name: 'Gnocchi di nonna Alice' },
  { id: 57, name: 'Ravioli Angelo' },
  { id: 58, name: 'Escargots de Bourgogne' },
  { id: 59, name: 'Raclette Courdavault' },
  { id: 60, name: 'Camembert Pierrot' },
  { id: 61, name: "Sirop d'érable" },
  { id: 62, name: 'Tarte au sucre' },
  { id: 63, name: 'Vegie-spread' },
  { id: 64, name: 'Wimmers gute Semmelknödel' },
  { id: 65, name: 'Louisiana Fiery Hot Pepper Sauce' },
  { id: 66, name: 'Louisiana Hot Spiced Okra' },
  { id: 67, name: 'Laughing Lumberjack Lager' },
  { id: 68, name: 'Scottish Longbreads' },
  { id: 69, name: 'Gudbrandsdalsost' },
  { id: 70, name: 'Outback Lager' },
  { id: 71, name: 'Flotemysost' },
  { id: 72, name: 'Mozzarella di Giovanni' },
  { id: 73, name: 'Röd Kaviar' },
  { id: 74, name: 'Longlife Tofu' },
  { id: 75, name: 'Rhönbräu Klosterbier' },
  { id: 76, name: 'Lakkalikööri' },
  { id: 77, name: 'Original Frankfurter grüne Soße' },
];

export const simpleProducts: string[] = [
  'Chai',
  'Chang',
  'Aniseed Syrup',
  "Chef Anton's Cajun Seasoning",
  "Chef Anton's Gumbo Mix",
  "Grandma's Boysenberry Spread",
  "Uncle Bob's Organic Dried Pears",
  'Northwoods Cranberry Sauce',
  'Mishi Kobe Niku',
  'Ikura',
  'Queso Cabrales',
  'Queso Manchego La Pastora',
  'Konbu',
  'Tofu',
  'Genen Shouyu',
  'Pavlova',
  'Alice Mutton',
  'Carnarvon Tigers',
  'Teatime Chocolate Biscuits',
  "Sir Rodney's Marmalade",
  "Sir Rodney's Scones",
  "Gustaf's Knäckebröd",
  'Tunnbröd',
  'Guaraná Fantástica',
  'NuNuCa Nuß-Nougat-Creme',
  'Gumbär Gummibärchen',
  'Schoggi Schokolade',
  'Rössle Sauerkraut',
  'Thüringer Rostbratwurst',
  'Nord-Ost Matjeshering',
  'Gorgonzola Telino',
  'Mascarpone Fabioli',
  'Geitost',
  'Sasquatch Ale',
  'Steeleye Stout',
  'Inlagd Sill',
  'Gravad lax',
  'Côte de Blaye',
  'Chartreuse verte',
  'Boston Crab Meat',
  "Jack's New England Clam Chowder",
  'Singaporean Hokkien Fried Mee',
  'Ipoh Coffee',
  'Gula Malacca',
  'Rogede sild',
  'Spegesild',
  'Zaanse koeken',
  'Chocolade',
  'Maxilaku',
  'Valkoinen suklaa',
  'Manjimup Dried Apples',
  'Filo Mix',
  'Perth Pasties',
  'Tourtière',
  'Pâté chinois',
  'Gnocchi di nonna Alice',
  'Ravioli Angelo',
  'Escargots de Bourgogne',
  'Raclette Courdavault',
  'Camembert Pierrot',
  "Sirop d'érable",
  'Tarte au sucre',
  'Vegie-spread',
  'Wimmers gute Semmelknödel',
  'Louisiana Fiery Hot Pepper Sauce',
  'Louisiana Hot Spiced Okra',
  'Laughing Lumberjack Lager',
  'Scottish Longbreads',
  'Gudbrandsdalsost',
  'Outback Lager',
  'Flotemysost',
  'Mozzarella di Giovanni',
  'Röd Kaviar',
  'Longlife Tofu',
  'Rhönbräu Klosterbier',
  'Lakkalikööri',
  'Original Frankfurter grüne Soße',
];
